spring:
  application:
    name: fuji-common
  datasource:
    url: jdbc:postgresql://192.168.31.115:5432/tek_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: tek_user
    password: tek_user
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080